{
 "title": "stellar-horizon-dashboard",
 "description": "This is a dashboard that shows some stats and information on stellar blockchain. This data is gathered from http://horizon.stellar.com. It displays statistics on number of operation such as payments, account_creation etc. It is intended to be run with Prometheus and the Stellar exporter (https://github.com/smorano/stellar-exporter).",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "sum payment last day",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum_over_time(total_amount_payment[1d])"
    }
   ]
  },
  {
   "title": "sum payment last hour",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum_over_time(total_amount_payment[1h])"
    }
   ]
  },
  {
   "title": "sum payment Change 15min",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 0 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum_over_time(total_amount_payment[15m]) - sum_over_time(total_amount_payment[15m] offset 15m)) / sum_over_time(total_amount_payment[15m])"
    }
   ]
  },
  {
   "title": "Nb operation / day",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum_over_time(nb_operation[1d])"
    }
   ]
  },
  {
   "title": "Nb operation Change 15min",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 0 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum_over_time(nb_operation[15m]) - sum_over_time(nb_operation[15m] offset 15m)) / sum_over_time(nb_operation[15m])"
    }
   ]
  },
  {
   "title": "Nb operation / hour",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum_over_time(nb_operation[1h])"
    }
   ]
  },
  {
   "title": "nb payement / day",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum_over_time(nb_operation_payment[1d])"
    }
   ]
  },
  {
   "title": "nb payement / hour",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum_over_time(nb_operation_payment[1h])"
    }
   ]
  },
  {
   "title": "nb_operation / 15min",
   "type": "graph",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum_over_time(nb_operation[15m])",
     "legendFormat": "nb_operation"
    }
   ]
  },
  {
   "title": "nb_operation_create_account / 15min",
   "type": "graph",
   "gridPos": { "h": 5, "w": 5, "x": 7, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum_over_time(nb_operation_create_account[15m])",
     "legendFormat": "nb_operation_create_account"
    }
   ]
  },
  {
   "title": "nb_operation_manage_data / 15min",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum_over_time(nb_operation_manage_data[15m])",
     "legendFormat": "nb_operation_manage_data"
    }
   ]
  },
  {
   "title": "total_amount_payment / 15min",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum_over_time(total_amount_payment[15m])",
     "legendFormat": "total_amount_payment"
    }
   ]
  },
  {
   "title": "nb_operation_payment / 15min",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum_over_time(nb_operation_payment[15m])",
     "legendFormat": "nb_operation_payment"
    }
   ]
  },
  {
   "title": "nb_operation_manage_offer / 15min",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 7, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum_over_time(nb_operation_manage_offer[15m])",
     "legendFormat": "nb_operation_manage_offer"
    }
   ]
  },
  {
   "title": "nb_operation_change_trust / 15min",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum_over_time(nb_operation_change_trust[15m])",
     "legendFormat": "nb_operation_change_trust"
    }
   ]
  },
  {
   "title": "nb_operation_path_payment / 15min",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum_over_time(nb_operation_path_payment[15m])",
     "legendFormat": "nb_operation_path_payment"
    }
   ]
  },
  {
   "title": "nb_operation_account_merge / 15min",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum_over_time(nb_operation_account_merge[15m])",
     "legendFormat": "nb_operation_account_merge"
    }
   ]
  },
  {
   "title": "sum_payment_by_asset / 15min",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 7, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum_over_time(sum_payment{asset=~\".*\"}[15m])",
     "legendFormat": "{{asset}}"
    }
   ]
  },
  {
   "title": "sum_payment native / 15min",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum_over_time(sum_payment{asset=~\"native\"}[15m])",
     "legendFormat": "sum_payment"
    }
   ]
  },
  {
   "title": "nb_payment_by_asset / 15min",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum_over_time(nb_payment{asset=~\".*\"}[15m])",
     "legendFormat": "{{ asset }}"
    }
   ]
  },
  {
   "title": "sum_payment native per minute",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum_payment{asset=~\"native\"}",
     "legendFormat": "sum_payment"
    }
   ]
  },
  {
   "title": "large native payments",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "sum_large_native_payment{from_addr=~\".*\", to_addr=~\".*\"}",
     "legendFormat": "{{ from_addr }}"
    }
   ]
  },
  {
   "title": "very large native payments (> 1M XLM)",
   "type": "table",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "sum_large_native_payment{from_addr=~\".*\", to_addr=~\".*\"} > 1000000",
     "legendFormat": "{{ from_addr }}"
    }
   ]
  }
 ]
}